Task 2
Savotii/spring pull request #2
Opened 2018-01-03 12:47 UTC by Savotii

2018-01-08 06:46 UTC, melgenek requested changes

2018-01-08 06:46 UTC, melgenek commented on src/main/resources/application-context.xml
> +        <property name="helper" ref="mySqlHelper" />
лишний, скорее всего

2018-01-08 06:46 UTC, melgenek commented on src/main/resources/application-context.xml
> +    <!--<bean name="basketRowMapper" class="com.andersen.spring.entity.BasketRowMapper">
не оставляй комментированный код

2018-01-08 06:46 UTC, melgenek commented on src/main/resources/application-context.xml
> +    <bean name="mySqlHelper" class="com.andersen.spring.jdbc.MySqlHelper" init-method="init"/>
Хелпер не нужен.
Таблицы создают заранее в базе. Создай файлик tables.sql где-то в корне проекта, который нужно будет выполнить, чтоб все работало.
Если хочешь, то можешь почитать про database migrations и такое фреймворки, как liquibase или flyway, которые решают проблему накатывания sql

2018-01-08 06:46 UTC, melgenek commented on src/main/java/com/andersen/spring/impl/UserDAOImpl.java
> +    private DataSource dataSource;
скорее всего - это лишнее

2018-01-08 06:46 UTC, melgenek commented on src/main/java/com/andersen/spring/impl/UserAccountDAOImpl.java
> +    private MySqlHelper helper;
не нужен

2018-01-08 06:46 UTC, melgenek commented on src/main/java/com/andersen/spring/impl/UserAccountDAOImpl.java
> +    private DataSource dataSource;
не нужен

2018-01-08 06:46 UTC, melgenek commented on src/main/java/com/andersen/spring/impl/ProductDAOImpl.java
> +            product = item;
может item сразу и вернуть, без дополнительных объектов?

2018-01-08 06:46 UTC, melgenek commented on src/main/java/com/andersen/spring/facade/MarketFacadeImpl.java
> +    public void replenishTheAccount(UserAccount account, Double amount) {
скорее всего, хватит одного метода updateBalance вместо replenishTheAccount и reduceTheAccount. И передавать положительный баланс при добавлении и отрицательный при снятии средств

2018-01-08 06:46 UTC, melgenek commented on src/main/java/com/andersen/spring/exceptions/InsufficientFunds.java
> +
давай здесь super("какое-то сообщение")

2018-01-08 06:46 UTC, melgenek commented on src/main/java/com/andersen/spring/exceptions/InsufficientFunds.java
> +public class InsufficientFunds extends Exception {
от RuntimeException наследовать следует. Это показывает, что exception unchecked

2018-01-08 06:46 UTC, melgenek commented on src/main/java/com/andersen/spring/impl/UserAccountServiceImpl.java
> +            updAccount.reduceTheAccount(amount);
А в базу сохранить?
Кажется, что метод на UserAccount не нужен. Просто обновить на уровне базы

2018-01-08 06:46 UTC, melgenek commented on src/main/java/com/andersen/spring/entity/UserAccount.java
> +    public void reduceTheAccount(Double amount) throws InsufficientFunds {
POJO-класс вряд ли должен содеражать логику, а только поля с данными

2018-01-08 06:46 UTC, melgenek commented on src/main/java/com/andersen/spring/entity/UserAccount.java
> +    private int accountsNumber;
не совсем понял смысл этого поля

2018-01-08 06:46 UTC, melgenek commented on src/main/java/com/andersen/spring/entity/UserAccount.java
> +    @Autowired
Здесь такое не отработает, бин не  в контексте. Да и смысл инжектить какого-то случайного пользователя

2018-01-08 06:46 UTC, melgenek commented on src/main/java/com/andersen/spring/entity/UserAccount.java
> +    private long userId;
уже есть user с айдишником, нет смысла дублировать

2018-01-08 06:46 UTC, melgenek commented on src/main/java/com/andersen/spring/entity/BasketRowMapper.java
> +@Scope("prototype")
prototype?

2018-01-08 06:46 UTC, melgenek commented on src/main/java/com/andersen/spring/entity/UserAccountRowMapper.java
> +        //Тут фигня. не прокидывает юзерсервис..
потому что ты в dao создаешь через new UserAccountRowMapper (), а не берешь созданный в xml спринговый бин userAccountRowMapper

2018-01-08 06:46 UTC, melgenek commented on src/main/java/com/andersen/spring/impl/UserAccountServiceImpl.java
> +    public UserAccount getUserAccount()
Этот метод реально нужен?  Смысла в lookup-method тут, кажется, нет

2018-01-08 06:46 UTC, melgenek commented on src/main/java/com/andersen/spring/facade/MarketFacadeImpl.java
> +    public void reduceTheAccount(UserAccount account, Double amount) {
reduceTheAccount и replenishTheAccount в фасаде не потребуются. Извне эти методы не вызываются. Представь, что кому-то доступен общедоступный метод снятия денег у случайного человека - небезопасно кажется

2018-01-08 06:46 UTC, melgenek commented on src/main/java/com/andersen/spring/entity/Product.java
> +     private User user;
userId и user одновременно. Что-то лишнее

2018-01-08 06:46 UTC, melgenek commented on src/main/resources/application-context.xml
> +    <bean name="basket" class="com.andersen.spring.entity.Basket" scope="prototype"/>
Думаю что prototype pojo стоит поудалять - никаких предзаполненных полей в нашем случае нет

2018-01-08 06:46 UTC, melgenek commented on src/main/java/com/andersen/spring/facade/MarketFacadeImpl.java
> +        basketServiceImpl.buyProduct(user, product, count);
Давай упростим. Представим, что есть мгновенная покупка. В результате покупки у продукта уменьшается количество или флажок "продано" выставляется, или даже ничего не происходит - неограниченное количество товара (доставят позже, к примеру).
Соответсвенно basket можно упразднить( в случае мгновенной покупки создается заказ Order. Отличие от корзины: заказ не модифицируем)

Тут суть в другом. У продукта есть владелец. Значит, при покупке, владельцу начислятся деньги, а у покупателя эти деньги снимутся. Это и будет считать покупкой. Такое перечисление денег должно быть атомарно, т.е. в транзакции

2018-01-08 06:46 UTC, melgenek commented on src/main/java/com/andersen/spring/facade/MarketFacadeImpl.java
> +    @Transactional
Просто так аннотация работать не будет. Требуется настройка в спринге.

Реализация метода будет примерно такой:
- снять деньги у покупателя
- начислить денег продавцу

Проверить, что транзакционность работает можно таким образом:
временно модифицируем "начислить денег продавцу", чтоб выбрасывалась ошибка(просто для проверки, потом уберем). Выполнить метод покупки и увидеть, что деньги на месте, т.к. транзация откатилась. Если у первого деньги все же снялиь, то нет атомарности и транзация не работает

2018-01-08 06:54 UTC, Savotii commented on src/main/java/com/andersen/spring/impl/ProductDAOImpl.java
> +            product = item;
Поправил.

2018-01-08 06:58 UTC, Savotii commented on src/main/java/com/andersen/spring/impl/UserAccountDAOImpl.java
> +    private MySqlHelper helper;
поправил.

2018-01-08 06:59 UTC, Savotii commented on src/main/java/com/andersen/spring/impl/UserAccountDAOImpl.java
> +    private DataSource dataSource;
поправил.

2018-01-08 07:00 UTC, Savotii commented on src/main/java/com/andersen/spring/impl/UserAccountServiceImpl.java
> +    public UserAccount getUserAccount()
Убрал.

2018-01-08 07:02 UTC, Savotii commented on src/main/java/com/andersen/spring/exceptions/InsufficientFunds.java
> +
+

2018-01-08 07:03 UTC, Savotii commented on src/main/java/com/andersen/spring/exceptions/InsufficientFunds.java
> +public class InsufficientFunds extends Exception {
+

2018-01-08 07:03 UTC, Savotii commented on src/main/java/com/andersen/spring/exceptions/InsufficientFunds.java
> +public class InsufficientFunds extends Exception {
+ поправил.

2018-01-08 07:03 UTC, Savotii commented on src/main/java/com/andersen/spring/exceptions/InsufficientFunds.java
> +
+ поправил.

2018-01-08 07:04 UTC, Savotii commented on src/main/java/com/andersen/spring/entity/UserAccountRowMapper.java
> +        //Тут фигня. не прокидывает юзерсервис..
с этим я уже разобрался, забыл поправить. Спасибо.

2018-01-08 14:42 UTC, Savotii commented on src/main/java/com/andersen/spring/entity/UserAccount.java
> +    private long userId;
Убрал.

2018-01-08 14:43 UTC, Savotii commented on src/main/java/com/andersen/spring/entity/UserAccount.java
> +    @Autowired
Убрал.

2018-01-08 14:44 UTC, Savotii commented on src/main/java/com/andersen/spring/entity/UserAccount.java
> +    private int accountsNumber;
пытался сымитировать номер счета.

2018-01-08 14:45 UTC, Savotii commented on src/main/java/com/andersen/spring/entity/BasketRowMapper.java
> +@Scope("prototype")
Попытка заставить бин работать, забыл убрать. Думал при связки с new может создавал бы. не получилось.
Убрал.

2018-01-09 06:42 UTC, Savotii commented on src/main/java/com/andersen/spring/entity/Product.java
> +     private User user;
+ Поправил.

2018-01-09 06:57 UTC, Savotii commented on src/main/java/com/andersen/spring/impl/UserAccountServiceImpl.java
> +            updAccount.reduceTheAccount(amount);
Поправил.

2018-01-09 06:58 UTC, Savotii commented on src/main/resources/application-context.xml
> +    <!--<bean name="basketRowMapper" class="com.andersen.spring.entity.BasketRowMapper">
Убрал

2018-01-09 06:58 UTC, Savotii commented on src/main/java/com/andersen/spring/facade/MarketFacadeImpl.java
> +    public void reduceTheAccount(UserAccount account, Double amount) {
+ Поправил.

2018-01-09 12:21 UTC, Savotii commented on src/main/java/com/andersen/spring/impl/UserDAOImpl.java
> +    private DataSource dataSource;
поубирал

2018-01-09 12:21 UTC, Savotii commented on src/main/resources/application-context.xml
> +    <bean name="basket" class="com.andersen.spring.entity.Basket" scope="prototype"/>
убрал

2018-01-09 12:22 UTC, Savotii commented on src/main/resources/application-context.xml
> +    <bean name="mySqlHelper" class="com.andersen.spring.jdbc.MySqlHelper" init-method="init"/>
создал, переделал. класс правда оставил. на посмотреть.

2018-01-09 12:22 UTC, Savotii commented on src/main/resources/application-context.xml
> +        <property name="helper" ref="mySqlHelper" />
убрал.

2018-01-09 12:23 UTC, Savotii commented on src/main/java/com/andersen/spring/facade/MarketFacadeImpl.java
> +        basketServiceImpl.buyProduct(user, product, count);
Переделал.

2018-01-09 12:23 UTC, Savotii commented on src/main/java/com/andersen/spring/facade/MarketFacadeImpl.java
> +    @Transactional
Переделал, транзакцию через спринг пока не осилил, сделал кодом.

2018-01-09 12:23 UTC, Savotii commented on src/main/java/com/andersen/spring/facade/MarketFacadeImpl.java
> +    public void replenishTheAccount(UserAccount account, Double amount) {
Переделал на updateBalance

2018-01-09 12:23 UTC, Savotii commented on src/main/java/com/andersen/spring/entity/UserAccount.java
> +    public void reduceTheAccount(Double amount) throws InsufficientFunds {
убрал.

2018-01-09 16:26 UTC, melgenek requested changes

2018-01-09 16:26 UTC, melgenek commented on src/main/java/com/andersen/spring/facade/MarketFacadeImpl.java
> +    @Transactional
Используй TransactionTemplate тогда

2018-01-09 16:26 UTC, melgenek commented on src/main/java/com/andersen/spring/facade/MarketFacadeImpl.java
> +    public MarketFacadeImpl(ProductServiceImpl productServiceImpl, UserServiceImpl userServiceImpl, UserAccountServiceImpl userAccountImpl) {
userAccountService, а не userAccountImpl

аргументы конструктора делай интерфейсами, а не реализациями

2018-01-09 16:26 UTC, melgenek commented on src/main/java/com/andersen/spring/impl/userAccount/UserAccountServiceImpl.java
> +       // sellerAccount = userAccountDAO.updateBalance(sellerAccount, product.getPrice());
забыл раскоментировать

И добавление денег на счет тоже в if стоит внести.
В случае, если денег недостаточно, то в else выбросить ошибку

2018-01-09 16:26 UTC, melgenek commented on src/main/java/com/andersen/spring/entity/Basket.java
> +public class Basket {
Корзина, дао и сервис на корзину ведь больше нигде не используется? Удалить бы

2018-01-09 17:54 UTC, Savotii commented on src/main/java/com/andersen/spring/facade/MarketFacadeImpl.java
> +    @Transactional
+ Переделал.

2018-01-09 17:54 UTC, Savotii commented on src/main/java/com/andersen/spring/entity/Basket.java
> +public class Basket {
+ Удалил.

2018-01-09 17:55 UTC, Savotii commented on src/main/java/com/andersen/spring/facade/MarketFacadeImpl.java
> +    public MarketFacadeImpl(ProductServiceImpl productServiceImpl, UserServiceImpl userServiceImpl, UserAccountServiceImpl userAccountImpl) {
Заменил.

2018-01-09 18:20 UTC, Savotii commented on src/main/java/com/andersen/spring/impl/userAccount/UserAccountServiceImpl.java
> +       // sellerAccount = userAccountDAO.updateBalance(sellerAccount, product.getPrice());
вынес throw из check.

2018-01-09 18:21 UTC, merged